# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
{
  pkgs,
  pythonEnv,
  llvm
}: let
  bitstream_path = "build/lowrisc_mocha_chip_mocha_genesys2_0/synth-vivado";
  bootrom_path = "build/sw/device/bootrom";
in {
  bitstream-hash = pkgs.writeShellApplication {
    name = "bitstream-hash";
    runtimeInputs = [pythonEnv llvm pkgs.gnumake pkgs.cmake pkgs.srecord];
    text = ''
      # Ask fusesoc to evaluate and generate the dependencies list.
      fusesoc --cores-root=. run --target=synth --setup lowrisc:mocha:chip_mocha_genesys2 > /dev/null 2>&1
      
      # Build the bootROM because it's cheap, and copy the vmem to the src to be hashed.
      cmake -DCMAKE_BUILD_TYPE=Release -B build/sw -S sw  > /dev/null 2>&1
      cmake --build build/sw --target bootrom > /dev/null 2>&1
      cp ${bootrom_path}/bootrom.vmem ${bitstream_path}

      # Hash the dependency list generated by fusesoc
      nix hash path ${bitstream_path}
    '';
  };

  bitstream-build = pkgs.writeShellApplication {
    name = "bitstream-build";
    runtimeInputs = [pythonEnv llvm pkgs.gnumake pkgs.cmake pkgs.srecord];
    text = ''
      cmake -B build/sw -S sw
      cmake --build build/sw --target bootrom

      fusesoc --cores-root=. run --target=synth --setup \
        --build lowrisc:mocha:chip_mocha_genesys2 \
        --BootRomInitFile="$PWD/${bootrom_path}/bootrom.vmem"
    '';
  };

  bitstream-load = pkgs.writeShellApplication {
    name = "bitstream-load";
    runtimeInputs = [pkgs.openfpgaloader];
    text = ''
      openFPGALoader -b genesys2 ${bitstream_path}/lowrisc_mocha_chip_mocha_genesys2_0.bit
    '';
  };
}
