// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_peri package generated by `tlgen.py` tool

package tl_peri_pkg;

  localparam logic [31:0] ADDR_SPACE_UART  = 32'h 41000000;
  localparam logic [31:0] ADDR_SPACE_TIMER = 32'h 44000000;

  localparam logic [31:0] ADDR_MASK_UART  = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_TIMER = 32'h 0000ffff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 2;

  typedef enum int {
    TlUart = 0,
    TlTimer = 1
  } tl_device_e;

  typedef enum int {
    TlAxiXbar = 0
  } tl_host_e;

endpackage
