// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_peri module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// axi_xbar
//   -> s1n_2
//     -> uart

module xbar_peri (
  input clk_i,
  input rst_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_axi_xbar_i,
  output tlul_pkg::tl_d2h_t tl_axi_xbar_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_uart_o,
  input  tlul_pkg::tl_d2h_t tl_uart_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_peri_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_2_us_h2d ;
  tl_d2h_t tl_s1n_2_us_d2h ;


  tl_h2d_t tl_s1n_2_ds_h2d [1];
  tl_d2h_t tl_s1n_2_ds_d2h [1];

  // Create steering signal
  logic [0:0] dev_sel_s1n_2;



  assign tl_uart_o = tl_s1n_2_ds_h2d[0];
  assign tl_s1n_2_ds_d2h[0] = tl_uart_i;

  assign tl_s1n_2_us_h2d = tl_axi_xbar_i;
  assign tl_axi_xbar_o = tl_s1n_2_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_2 = 1'd1;
    if ((tl_s1n_2_us_h2d.a_address &
         ~(ADDR_MASK_UART)) == ADDR_SPACE_UART) begin
      dev_sel_s1n_2 = 1'd0;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .N         (1)
  ) u_s1n_2 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_s1n_2_us_h2d),
    .tl_h_o       (tl_s1n_2_us_d2h),
    .tl_d_o       (tl_s1n_2_ds_h2d),
    .tl_d_i       (tl_s1n_2_ds_d2h),
    .dev_select_i (dev_sel_s1n_2)
  );

endmodule
