// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"uart", '{
        '{32'h41000000, 32'h41000fff}
    }},
    '{"timer", '{
        '{32'h44000000, 32'h4400ffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"axi_xbar", 0, '{
        "uart",
        "timer"}}
};
