# Licenses and Copyright for Generated hardware components

version = 1

[[annotations]]
path = ["ip_autogen/rv_plic/**"]
SPDX-FileCopyrightText = "lowRISC Contributors (OpenTitan project)."
SPDX-License-Identifier = "Apache-2.0"
