#!/usr/bin/env python
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

import argparse
import json
import sys
from pathlib import Path

import jinja2


def human_size(num, suffix="B"):
    for unit in ["", "ki", "Mi", "Gi", "Ti", "Pi"]:
        if abs(num) < 1024:
            return f"{num:3.1f} {unit}{suffix}"
        num /= 1024

def gen_from_template(input_file: Path, out_file: Path, template: str, comment_scape: str = "//"):
    """Process a template and generate a file."""

    print(f"Loading file: {input_file}...")
    with input_file.open("r") as f:
        rdljson = json.load(f)

    for device in rdljson["devices"]:
       device["human_size"] = human_size(device["size"]) 

    template = jinja2.Template(template)

    with out_file.open("a") as f:
        f.write(template.render(rdljson))
        f.write("\n")

    print(f"Successfully generated {out_file}")


def get_command_line() -> str:
    args = []
    for item in sys.argv:
        if Path(item).exists():
            args.append(str(Path(item).resolve().relative_to(Path.cwd())))
        else:
            args.append(item)
    return " ".join(args)


# REUSE-IgnoreStart
LICENSE_HEADER = """Copyright lowRISC contributors (COSMIC project).
Licensed under the Apache License, Version 2.0, see LICENSE for details.
SPDX-License-Identifier: Apache-2.0
"""
# REUSE-IgnoreEnd

LD_TEMPLATE = """
MEMORY {
{%- for device in devices %}
  {%- set base_addr = device.offset if device.offset else device.offsets[0] %}
    {%- if device.type == "mem" %}
        {%- set name = device.name %}
        {%- set addr = base_addr %}
        {%- set size = device.size %}
        {%- set hsize = device.human_size %}
    {{"{:<10}: ORIGIN = {:#010x}, LENGTH = {:#010x} /* {:>6} */".format(name, addr, size, hsize)}}
    {%- endif %}
{%- endfor %}
}
"""


def gen_linker_script(args) -> None:
    """Generate a linker file with the memory map."""

    input_file = Path(args.input_file)
    out_file = Path(args.out_file)

    cmd = get_command_line()
    with out_file.open("w") as f:
        for line in LICENSE_HEADER.splitlines():
            f.write(f"/* {line} */\n")
        f.write(f"/* Auto-generated: '{cmd}' */")
    gen_from_template(input_file, out_file, LD_TEMPLATE)


def main():
    parser = argparse.ArgumentParser(description="Systemrdl generator utility")
    subparsers = parser.add_subparsers(dest="command", required=True, help="Sub-commands")

    # Subparser for gen_linker_script
    linker_parser = subparsers.add_parser(
        "gen-linker-script", help="Generate a linker file with the memory map."
    )
    linker_parser.add_argument("input_file", help="Input JSON file generated by rdl2ot")
    linker_parser.add_argument(
        "out_file",
        nargs="?",
        default="./build/memory.ld",
        help="Output filename (default: ./build/memory.ld)",
    )
    linker_parser.set_defaults(func=gen_linker_script)

if __name__ == "__main__":
    main()

