#!/usr/bin/env python
# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

import argparse
import json
import sys
from pathlib import Path
from typing import TextIO

import jinja2
import svgwrite


def human_size(num, suffix="B"):
    for unit in ["", "ki", "Mi", "Gi", "Ti", "Pi"]:
        if abs(num) < 1024:
            return f"{num:3.1f} {unit}{suffix}"
        num /= 1024


def gen_from_template(input_file: Path, out_file: Path, template: str, comment_scape: str = "//"):
    """Process a template and generate a file."""

    print(f"Loading file: {input_file}...")
    with input_file.open("r") as f:
        rdljson = json.load(f)

    for device in rdljson["devices"]:
        device["human_size"] = human_size(device["size"])

    template = jinja2.Template(template)

    with out_file.open("a") as f:
        f.write(template.render(rdljson))
        f.write("\n")

    print(f"Successfully generated {out_file}")


def get_command_line() -> str:
    args = []
    for item in sys.argv:
        if Path(item).exists():
            args.append(str(Path(item).resolve().relative_to(Path.cwd())))
        else:
            args.append(item)
    return " ".join(args)


# REUSE-IgnoreStart
LICENSE_HEADER = """Copyright lowRISC contributors (COSMIC project).
Licensed under the Apache License, Version 2.0, see LICENSE for details.
SPDX-License-Identifier: Apache-2.0
"""
# REUSE-IgnoreEnd


def emit_file_header(file: TextIO, comment_open: str = "", comment_close: str = "") -> None:
    """Emit a file header consisting of the project's license header and a line showing
    what command was invoked to generate it, wrapped in comments."""
    for line in LICENSE_HEADER.splitlines():
        file.write(f"{comment_open}{line}{comment_close}\n")
    file.write(f"{comment_open}Auto-generated: '{get_command_line()}'{comment_close}\n")


LD_TEMPLATE = """
MEMORY {
{%- for device in devices %}
  {%- set base_addr = device.offset if device.offset else device.offsets[0] %}
    {%- if device.type == "mem" %}
        {%- set name = device.name %}
        {%- set addr = base_addr %}
        {%- set size = device.size %}
        {%- set hsize = device.human_size %}
    {{"{:<10}: ORIGIN = {:#010x}, LENGTH = {:#010x} /* {:>6} */".format(name, addr, size, hsize)}}
    {%- endif %}
{%- endfor %}
}
"""


def gen_linker_script(args) -> None:
    """Generate a linker file with the memory map."""

    input_file = Path(args.input_file)
    out_file = Path(args.out_file)

    with out_file.open("w") as f:
        emit_file_header(f, comment_open="/* ", comment_close=" */")
    gen_from_template(input_file, out_file, LD_TEMPLATE)


def gen_memory_map(args) -> None:
    """Generate a svg file with the memory map."""

    input_file = Path(args.input_file)
    out_file = Path(args.out_file)

    print(f"Loading file: {input_file}...")
    with input_file.open("r") as f:
        rdljson = json.load(f)

    cell_w = 160
    cell_h = 30
    rows_n = len(rdljson["devices"]) + 1
    cols = 4

    dwg = svgwrite.Drawing(out_file, size=(cell_w * cols, cell_h * rows_n))
    font = {"font_size": 14, "font_family": "monospace"}

    # Header
    header = ["Base address", "Top address", "Reserved", "Function"]
    for c, h in enumerate(header):
        x = c * cell_w
        dwg.add(dwg.rect((x, 0), (cell_w, cell_h), fill="black", stroke="white"))
        dwg.add(dwg.text(h, insert=(x + 6, 20), **font, fill="white"))

    # Rows
    for r, device in enumerate(rdljson["devices"], start=1):
        base_addr = device["offset"] if "offset" in device else device["offsets"][0]
        end_addr = base_addr + device["size"] - 1
        size = human_size(device["size"])
        line = [f"{base_addr:#010x}", f"{end_addr:#010x}", size, device["name"]]
        for c, cell in enumerate(line):
            x = c * cell_w
            y = r * cell_h
            dwg.add(dwg.rect((x, y), (cell_w, cell_h), fill="white", stroke="black"))
            dwg.add(dwg.text(cell, insert=(x + 6, y + 20), **font))

    dwg.save()


def gen_device_register_c_headers(args) -> None:
    pass


def main():
    parser = argparse.ArgumentParser(description="Systemrdl generator utility")
    subparsers = parser.add_subparsers(dest="command", required=True, help="Sub-commands")

    # Subparser for gen_linker_script
    linker_parser = subparsers.add_parser(
        "gen-linker-script", help="Generate a linker file with the memory map."
    )
    linker_parser.add_argument("input_file", type=Path, help="Input JSON file generated by rdl2ot")
    linker_parser.add_argument(
        "out_file",
        type=Path,
        nargs="?",
        default=Path("./build/memory.ld"),
        help="Output filename. (default: %(default)s)",
    )
    linker_parser.set_defaults(func=gen_linker_script)

    # Subparser for gen_memory_map
    map_parser = subparsers.add_parser(
        "gen-memory-map", help="Generate a svg file with the memory map."
    )
    map_parser.add_argument("input_file", type=Path, help="Input JSON file generated by rdl2ot")
    map_parser.add_argument(
        "out_file",
        type=Path,
        nargs="?",
        default=Path("./build/memmap.svg"),
        help="Output filename. (default: %(default)s)",
    )
    map_parser.set_defaults(func=gen_memory_map)

    # Subparser for gen_register_dif
    register_parser = subparsers.add_parser(
        "gen-device-headers", help="Generate device register interface C headers."
    )
    register_parser.add_argument(
        "input_file", type=Path, help="Input JSON file generated from rdl2ot"
    )
    register_parser.add_argument(
        "out_dir",
        type=Path,
        nargs="?",
        default=Path("./sw/device/lib/hal/autogen"),
        help="Output directory for auto-generated register DIF code. (default: %(default)s)",
    )
    register_parser.set_defaults(func=gen_device_register_c_headers)

    # Parse and execute
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
