# Copyright lowRISC Contributors (COSMIC project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: "nix develop -c bash -e {0}"

    steps:
      - uses: actions/checkout@v5

      - name: License check
        uses: fsfe/reuse-action@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            substituters = https://nix-cache.lowrisc.org/public/ https://cache.nixos.org/
            trusted-public-keys = nix-cache.lowrisc.org-public-1:O6JLD0yXzaJDPiQW1meVu32JIDViuaPtGDfjlOopU7o= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Prepare Nix environment
        run: |
          true

      - name: Lint - Ruff
        run: |
          ruff check

      - name: Lint - Check Lockfiles
        run: |
          util/lockfiles_check.sh

      - name: Lint - Check Crossbar
        run: |
          util/xbar_check.sh

      - name: Lint - Check Vendor
        run: |
          util/vendor_check.sh

      - name: Generate software buildsystem
        run: |
          cmake -B build/sw -S sw

      - name: Lint - Clang Format
        run: |
          util/clang_format.py -i --dry-run -Werror

      - name: Lint - Clang Tidy
        run: |
          util/clang_tidy.py

      - name: Build software
        run: |
          cmake --build build/sw -j $(nproc)

      - name: Build verilator
        run: |
          fusesoc --cores-root=. run --target=sim --tool=verilator --setup --build lowrisc:mocha:top_chip_system

      - name: Run verilator software tests
        run: |
          ctest --test-dir build/sw -R sim_verilator
