# Copyright lowRISC Contributors (COSMIC project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  # This job will only succeed if a bitstream was published by a previous CI run to make sure it
  # passed the tests.
  bistream-release:
    runs-on: ["self-hosted", "nixos", "X64"]
    env:
      BITSTREAM: build/lowrisc_mocha_chip_mocha_genesys2_0/synth-vivado/lowrisc_mocha_chip_mocha_genesys2_0.bit
      UTILIZATION_FILE: build/lowrisc_mocha_chip_mocha_genesys2_0/synth-vivado/lowrisc_mocha_chip_mocha_genesys2_0.runs/impl_1/chip_mocha_genesys2_utilization_placed.rpt

    steps:
    - uses: actions/checkout@v5

    - name: Hash Bitstream
      id: hash-bitstream
      run: |
        echo "hash=$(nix run .#bitstream-hash)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v5
      id: cache
      with:
        path: |
          ${{ env.BITSTREAM }}
          ${{ env.UTILIZATION_FILE }}
        key: ${{ steps.hash-bitstream.outputs.hash }}
        fail-on-cache-miss: true

    - uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        prerelease: true
        files: |
          ${{ env.BITSTREAM }}
          ${{ env.UTILIZATION_FILE }}

  verilator-release:
    runs-on: ["self-hosted", "nixos", "X64"]
    env:
      ARTEFACT: build/lowrisc_mocha_top_chip_verilator_0/sim-verilator/Vtop_chip_verilator

    defaults:
      run:
        shell: "nix develop -c bash -e {0}"

    steps:
      - uses: actions/checkout@v5

      - name: Prepare Nix environment
        run: |
          true

      - name: Build verilator
        run: |
          JOBS=$(($(nproc) / 2))
          MAKEFLAGS="-j$JOBS" fusesoc --cores-root=. run --target=sim --tool=verilator --setup --build lowrisc:mocha:top_chip_verilator

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          prerelease: true
          files: ${{ env.ARTEFACT }}

  software-release:
    runs-on: ["self-hosted", "nixos", "X64"]
    env:
      SOURCE: build/sw/device/examples
      ARTEFACT: examples.tar.gz

    defaults:
      run:
        shell: "nix develop -c bash -e {0}"

    steps:
      - uses: actions/checkout@v5

      - name: Prepare Nix environment
        run: |
          true

      - name: Generate artefacts
        run: |
          cmake -B build/sw -S sw

          for t in hello_world hello_world_verilator; do
            cmake --build build/sw -j $(nproc) --target $t
            cmake --install build/sw/ --prefix release --component $t
          done

          tar -czvf ${{ env.ARTEFACT }} release

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          prerelease: true
          files: ${{ env.ARTEFACT }}
